//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo2.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ID_product { get; set; }
        public string Name_pr { get; set; }
        public Nullable<int> Articul { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Price { get; set; }
        public string Discription { get; set; }
    }
}
