//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo2.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int ID_user { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<int> ID_role { get; set; }
        public string FIO { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
